controller_list:
  - name: fake_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_joint
      - virtual_roll_joint
      - virtual_yaw_joint
  - name: fake_gripper_controller
    joints:
      - left_finger_joint
      - right_finger_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: up
  - group: gripper
    pose: closed